services:
  stats-server:
    ports:
      - "9090:9090"
    build:
      context: ./stats-server
      dockerfile: Dockerfile

  stats-db:
    image: postgres:16.1

  ewm-service:
    ports:
      - "8080:8080"
    build:
      context: ./ewm-service
      dockerfile: Dockerfile

  ewm-db:
    image: postgres:16.1
