services:
  stats-service:
    ports:
      - "9090:9090"
    build:
      context: ./stats
      dockerfile: Dockerfile

  stats-db:
    image: postgres:16.1

  ewm-service:
    ports:
      - "8080:8080"
    build:
      context: ./main-service
      dockerfile: Dockerfile

  ewm-db:
    image: postgres:16.1
