services:
  stats-server:
    image: stats-server-image
    ports:
      - "9090:9090"
    build: ./stats-server/server
    container_name: stats-server
    networks:
      - stat-net
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
        - SPRING_DATASOURCE_USERNAME=sa
        - SPRING_DATASOURCE_PASSWORD=pass

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6542:5432"
    environment:
        - POSTGRES_DB=stats-db
        - POSTGRES_USER=sa
        - POSTGRES_PASSWORD=pass
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - stat-net

  ewm-service:
    image: ewm-service-image
    ports:
      - "8080:8080"
    build:
      context: ./ewm-service
      dockerfile: Dockerfile
    depends_on:
        - ewm-db
    environment:
          - CLIENT_URL=http://stats-server:9090
          - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
          - SPRING_DATASOURCE_USERNAME=sa
          - SPRING_DATASOURCE_PASSWORD=pass


  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=pass

volumes:
    postgres:
networks:
    stat-net: